<?php
session_start();
define("APPURL", "http://localhost/Alwasit/");
$function = 'includes/functions/';
# Routes
$templates = 'includes/template/';
$owner = 'owner/';
$css = 'ar/css/';
$js = 'ar/js/';
$images = 'ar/images/';
$notFound = 'Not Found.php';
$home = 'index.php';
$contactus = 'تواصل_معنا.php';
$forRent = 'عقارات_للإيجار.php';
$forBuy = 'عقارات_للبيع.php';
$prop_details = "property_details.php";
$privacy_policy = 'سياسه_الخصوصية.php';
$students = 'الطلاب.php';
$commercial = 'عقارات_تجارية.php';
$about = 'عنا.php';
$instructions = 'التعليمات.php';
$services = 'خدماتنا.php';
$login = 'login.php';
$register = 'register.php';
$emails_libs = 'libs/emails/';
$config = 'config/';
$verification_page = 'verification.php';
$auth = 'auth/';
$logout = 'auth/logout.php';
$user = 'user/';
$libs = 'libs/';
